export const auditPerformanceLabels = {
  zh: {
    title: "请求耗时与重试", hint: "悬停或点击查看请求过程", total: "总耗时", first: "首字", after: "首字后至结束",
    selection: "账号选择", credential: "凭据准备", upstream: "上游调用", quality: "质量预读", finalAccount: "最终账号",
    calls: "网关调用 {{count}} 次", retries: "重试 {{count}} 次", switched: "换号 {{count}} 次", diagnostics: "诊断记录 {{count}} 条", timeline: "账号调用过程",
    legacy: "此记录未保存阶段计时（旧版本或未采集的请求类型）。下面仅展示已有诊断，不代表全部调用。",
    none: "未保存失败或换号诊断；这不等于确认没有重试。", noCalls: "尚未进入上游调用。",
    scope: "阶段计时以网关为准。上游调用包含适配器内部处理；流式正文读取不全在此项。质量预读单列，不与首字时间相加。",
    signalScope: "到达时间相对本次质量预读开始；“—”表示未观测到。", callScope: "调用次数按网关调用适配器计数；适配器内部恢复尝试另见诊断。",
    byte: "首个字节", thinking: "推理证据", visible: "可见输出", begin: "开始 +{{time}}", result: "请求结束", failure: "失败诊断",
    loadError: "请求过程加载失败", retry: "重新加载", details: "打开完整诊断", loading: "正在读取请求过程…",
    action_retry: "继续换号", action_reject: "停止并拒绝", action_deliver: "放流", action_deliver_last: "按兜底策略放流", action_fallback: "回用此响应兜底",
    response: "已收到响应", error: "调用异常", deliver: "检查通过", withhold: "质量拦截", timeout: "检查超时", empty: "上游空流", wait: "证据不足",
    quality_peek: "质量预读失败", quality_hold: "质量拦截", response_stream: "响应流中断", upstream_response: "上游返回错误",
    credential_validation: "凭据校验", credential_refresh: "凭据刷新", account_selection: "账号选择失败", response_body: "响应读取失败",
    response_header_timeout: "等待响应头超时", request_canceled: "请求取消", request_timeout: "请求超时", dns_lookup: "域名解析", tls_verification: "证书校验", tls_handshake: "TLS 握手", network_timeout: "网络超时", transport: "网络传输", reasoning_decode_rejected: "推理数据被拒绝", reasoning_session_reset: "推理会话重建",
  },
  en: {
    title: "Request timing & retries", hint: "Hover or click for request details", total: "Total", first: "First token", after: "After first token",
    selection: "Account selection", credential: "Credentials", upstream: "Upstream call", quality: "Quality pre-read", finalAccount: "Final account",
    calls: "{{count}} gateway calls", retries: "{{count}} retries", switched: "{{count}} account switches", diagnostics: "{{count}} diagnostic records", timeline: "Account call timeline",
    legacy: "Stage timings are unavailable for this record (older version or an uninstrumented request type). Saved diagnostics do not represent all calls.",
    none: "No failure or account-switch diagnostics were saved. This does not confirm that no retries occurred.", noCalls: "No upstream call was started.",
    scope: "Timings are measured in the gateway. Upstream includes adapter processing, not all streamed body reads. Quality pre-read is separate; do not add it to first-token time.",
    signalScope: "Arrival times are relative to this quality pre-read. — means not observed.", callScope: "Calls count gateway adapter invocations. Internal recovery attempts appear in diagnostics.",
    byte: "First byte", thinking: "Thinking evidence", visible: "Visible output", begin: "Start +{{time}}", result: "Request completed", failure: "Failure diagnostics",
    loadError: "Could not load request details", retry: "Retry", details: "Open full diagnostics", loading: "Loading request details…",
    action_retry: "Try another account", action_reject: "Stop and reject", action_deliver: "Release stream", action_deliver_last: "Release per fallback policy", action_fallback: "Use this response as fallback",
    response: "Response received", error: "Call failed", deliver: "Check passed", withhold: "Quality withheld", timeout: "Check timed out", empty: "Empty upstream stream", wait: "Insufficient evidence",
    quality_peek: "Quality pre-read failed", quality_hold: "Quality withheld", response_stream: "Stream interrupted", upstream_response: "Upstream error",
    credential_validation: "Credential validation", credential_refresh: "Credential refresh", account_selection: "Account selection failed", response_body: "Response read failed",
    response_header_timeout: "Response header timeout", request_canceled: "Request canceled", request_timeout: "Request timeout", dns_lookup: "DNS lookup", tls_verification: "Certificate verification", tls_handshake: "TLS handshake", network_timeout: "Network timeout", transport: "Network transport", reasoning_decode_rejected: "Reasoning data rejected", reasoning_session_reset: "Reasoning session reset",
  },
};
